-- Run this in Supabase SQL Editor

create table if not exists subjects (
  id bigint generated by default as identity primary key,
  name text not null,
  code text unique,
  description text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

create table if not exists classes (
  id bigint generated by default as identity primary key,
  subject_id bigint references subjects(id) on delete cascade,
  teacher_id uuid references auth.users(id), -- Assuming profiles.id is uuid and matches auth.users
  name text, -- Batch Name, e.g. "Grade 10 A"
  start_time time,
  end_time time,
  day_of_week text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- RLS Policies (Simple for now)
alter table subjects enable row level security;
alter table classes enable row level security;

create policy "Enable read access for all users" on subjects for select using (true);
create policy "Enable all access for admins" on subjects using (
  auth.uid() in (select id from profiles where role = 'admin')
);

create policy "Enable read access for all users" on classes for select using (true);
create policy "Enable all access for admins" on classes using (
  auth.uid() in (select id from profiles where role = 'admin')
);
