-- Run this in Supabase SQL Editor

-- Materials: Assignments, Notes, Videos
create table if not exists materials (
  id bigint generated by default as identity primary key,
  title text not null,
  description text,
  type text check (type in ('document', 'video', 'link')) default 'document',
  file_url text, -- URL to Supabase Storage or external link
  subject_id bigint references subjects(id) on delete cascade,
  created_by uuid references auth.users(id),
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- RLS
alter table materials enable row level security;

-- Policies
create policy "Read materials" on materials for select using (true);

create policy "Modify materials for staff" on materials for all using (
  auth.uid() in (select id from profiles where role in ('admin', 'teacher'))
);

-- Note: You also need to create a Storage Bucket named 'materials' in Supabase Dashboard
-- and set policy to allow public read, and auth insert/update.
