-- Run this in Supabase SQL Editor

-- Notices: Global Announcements
create table if not exists notices (
  id bigint generated by default as identity primary key,
  title text not null,
  content text not null,
  is_pinned boolean default false,
  created_by uuid references auth.users(id),
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Messages: Direct Messages
create table if not exists messages (
  id bigint generated by default as identity primary key,
  sender_id uuid references auth.users(id) not null,
  receiver_id uuid references auth.users(id) not null,
  content text not null,
  is_read boolean default false,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- RLS
alter table notices enable row level security;
alter table messages enable row level security;

-- Policies for Notices
create policy "Read notices" on notices for select using (true);
create policy "Modify notices for staff" on notices for all using (
  auth.uid() in (select id from profiles where role in ('admin', 'teacher'))
);

-- Policies for Messages
create policy "Read own messages" on messages for select using (
  auth.uid() = sender_id or auth.uid() = receiver_id
);

create policy "Send messages" on messages for insert with check (
  auth.uid() = sender_id
);

-- Note: Typically you need a profile-lookup policy to allow users to search others to message them.
-- Existing profile policies should handle reading names.
