-- Run this in Supabase SQL Editor

-- Exams: Scheduled exams for a subject
create table if not exists exams (
  id bigint generated by default as identity primary key,
  title text not null, -- e.g. "Mid-Term Exam"
  subject_id bigint references subjects(id) on delete cascade,
  date date not null,
  start_time time,
  end_time time,
  total_marks integer default 100,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Exam Results: Marks for each student
create table if not exists exam_results (
  id bigint generated by default as identity primary key,
  exam_id bigint references exams(id) on delete cascade,
  student_id uuid references auth.users(id) on delete cascade,
  marks_obtained numeric(5,2), -- Allows for 95.50
  grade text, -- e.g. 'A', 'B'
  remarks text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  unique(exam_id, student_id)
);

-- RLS
alter table exams enable row level security;
alter table exam_results enable row level security;

-- Policies for Exams
create policy "Read exams" on exams for select using (true);
create policy "Modify exams for staff" on exams for all using (
  auth.uid() in (select id from profiles where role in ('admin', 'teacher'))
);

-- Policies for Exam Results
create policy "Read results own or staff" on exam_results for select using (
  auth.uid() = student_id or 
  auth.uid() in (select id from profiles where role in ('admin', 'teacher'))
);

create policy "Modify results for staff" on exam_results for all using (
  auth.uid() in (select id from profiles where role in ('admin', 'teacher'))
);
