-- Run this in Supabase SQL Editor

-- Audit Logs: Track system actions
create table if not exists audit_logs (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users(id),
  action text not null, -- e.g. 'CREATED_USER', 'DELETED_CLASS'
  details text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- RLS
alter table audit_logs enable row level security;

-- Policies
create policy "Read audit logs for admin" on audit_logs for select using (
  auth.uid() in (select id from profiles where role = 'admin')
);

-- Allow authenticated users to create logs (e.g. "User X updated their profile")
create policy "Insert audit logs" on audit_logs for insert with check (
  auth.role() = 'authenticated'
);
