-- Run this in Supabase SQL Editor

-- Enrollments: Links Students to specific Class Schedule Slots
create table if not exists enrollments (
  id bigint generated by default as identity primary key,
  student_id uuid references auth.users(id) on delete cascade,
  class_id bigint references classes(id) on delete cascade,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  unique(student_id, class_id)
);

-- Attendance: Records attendance for a specific class on a specific date
create table if not exists attendance (
  id bigint generated by default as identity primary key,
  class_id bigint references classes(id) on delete cascade,
  student_id uuid references auth.users(id) on delete cascade,
  date date not null,
  status text check (status in ('present', 'absent', 'late', 'excused')) default 'present',
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  unique(class_id, student_id, date)
);

-- RLS
alter table enrollments enable row level security;
alter table attendance enable row level security;

-- Policies for Enrollments
create policy "Read enrollments" on enrollments for select using (true);
create policy "Modify enrollments for staff" on enrollments for all using (
  auth.uid() in (select id from profiles where role in ('admin', 'teacher'))
);

-- Policies for Attendance
create policy "Read attendance" on attendance for select using (true);
create policy "Modify attendance for staff" on attendance for all using (
  auth.uid() in (select id from profiles where role in ('admin', 'teacher'))
);
